### ISSUE TITLE
Add key signatures and mensuration signs in Census

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#20]

**Comment by craigsapp** [comment]
Done:

http://www.tassomusic.org/census

Two columns are added.   "Time" list the mensuration (either C or Cut-C) and "Key" giving the key signature (nothing listed if no sharps/flats in the keysignature, or no keysignature).  One flat means the key signature has one flat, for example.

Example:

<img width="1041" alt="screen shot 2017-04-08 at 9 40 54 am" src="https://cloud.githubusercontent.com/assets/3487289/24830700/cdd3c216-1c3f-11e7-8c2f-0cdad53348c8.png">

Clicking on the "Time" column header will sort the works by mensuration sign:

<img width="1072" alt="screen shot 2017-04-08 at 9 45 14 am" src="https://cloud.githubusercontent.com/assets/3487289/24830713/24b367d0-1c40-11e7-8a69-7d325c8576d0.png">

Clicking on the "Key" column header will sort the works by key signature:

<img width="1028" alt="screen shot 2017-04-08 at 9 46 16 am" src="https://cloud.githubusercontent.com/assets/3487289/24830717/3a874ffe-1c40-11e7-8f50-ba16ec3cbf9d.png">

**Comment by emilianoricciardi** [comment]
Note: I think we should change "time" to "mensuration," as there is another column marked "time" which lists playback length...

**Comment by craigsapp** [comment]
The problem is that that is too long to fit (notice that the titles are
starting to wrap.

**Comment by emilianoricciardi** [comment]
how about "time sign."?

**Comment by emilianoricciardi** [comment]
or maybe we can remove the "pages" column?

**Comment by craigsapp** [comment]
The census page is more for maintenance, so pages column is better to keep so that I can track cases where the PDF files mysteriously disappear.

Maybe change the column title to "mens." as an abbreviation for "mensuration".

The workpage without a catalog number input is more for general use, so less interesting to have the "pages" column there:

http://www.tassomusic.org/work

I can add the mensuration and key signatures to that listing of the works.

<img width="1103" alt="screen shot 2017-04-10 at 3 04 34 pm" src="https://cloud.githubusercontent.com/assets/3487289/24884599/088ac394-1dff-11e7-8813-764adc960b96.png">

The catalog number could also be removed from that page, or abbreviated to solerti number (or act, scene, etc. for Gerusalemme and Aminta).

**Comment by emilianoricciardi** [comment]
Sounds good, though I think we want to keep the catalog number in the work
list

On Mon, Apr 10, 2017 at 6:11 PM, Craig Stuart Sapp <notifications@github.com

**Comment by craigsapp** [comment]
I changed "Time" to "Mens." on the census page:

<img width="249" alt="screen shot 2017-04-11 at 8 07 42 am" src="https://cloud.githubusercontent.com/assets/3487289/24916070/f78a6f24-1e8d-11e7-9d69-1e488d76be9f.png">

And I added Key signature/Mensuration information to the worklist page which is displayed from the work page when there is no specific work to display a workpage for:

http://www.tassomusic.org/work


<img width="766" alt="screen shot 2017-04-11 at 8 04 04 am" src="https://cloud.githubusercontent.com/assets/3487289/24916118/1b0035ce-1e8e-11e7-841e-154fceef561f.png">

Clicking on the top of the columns will sort the key and mens. columns:

<img width="766" alt="screen shot 2017-04-11 at 8 04 15 am" src="https://cloud.githubusercontent.com/assets/3487289/24916149/2fabb93a-1e8e-11e7-8195-5b59b9a844a3.png">

<img width="767" alt="screen shot 2017-04-11 at 8 04 22 am" src="https://cloud.githubusercontent.com/assets/3487289/24916154/3278fca4-1e8e-11e7-83d6-9d02a7b3a413.png">
