### ISSUE TITLE
Critical report model template

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#25]
Create workpage template using Trm0047m workpage as a model.

**Comment by craigsapp** [comment]
Here is a draft of a critical-notes template, using the ATON system (ATON meaning "@ Object Notation in case you are wondering).  We can discuss this and refine it on Monday.  This template removes much of the formatting from the current [template](https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/data/reports/Trm0047m-report.html) and will therefore allow more adjustment of the layout later.

```
@@BEGIN: CRITICAL_REPORT

@CATALOGNUM: Trm0047m

@PRINCIPAL_SOURCE:
	<i>Fiori musicali di diversi auttori a tre voci.
	Libro secondo. Nuovamente composti, & dati in luce</i>.
	Venice: Giacomo Vincenzi, 1588 (RISM B/I, 1588-20)
	<br>
	[Princeps edition --- complete: CTB]
	<br>
	Digital reproduction of exemplar from {{siglum "A-Wn"}}


@OTHER_SOURCE:
	<i>Fiori musicali di diversi auttori a tre voci. Libro secondo.
	Nuovamente ristampati</i>. Venice: Giacomo Vincenti, 1598 (RISM B/I, 1598-10)
	<br>
	[Reprint of RISM B/I, 1588-20 --- complete: CTB]

@OTHER_SOURCE: Microfilm reproduction of exemplar from {{siglum "I-Bc"}}

@OTHER_SOURCE: <i>Fiori musicali a tre voci de diversi eccellentissimi auttori.
	Di nuovo stampati & seguendo l’ordine de suoi Tuoni posti in luce</i>.
	Antwerp: Pietro Phalesio, 1604 (RISM B/I, 1604-13)
	<br>
	[Pierre Phalèse’s reprint of the first and second books of the anthology
	<i>Fiori musicali</i> --- complete: CTB]

@OTHER_SOURCE: CB --- Microfilm reproduction of exemplar from {{siglum "B-Br"}}

@OTHER_SOURCE: T --- Digital reproduction of exemplar from {{siglum "DK-Kk"}}

@EMENDED_READING: None

@CRITICAL_NOTE: {{MM 14}} and {{MMx 18}}, T, text reads “forza o d’arte”
	and “forza od arre,” respectively.

@CRITICAL_NOTE: In corresponding sections from reprint RISM B/I,
	1598-10, text reads “forza d’arte” consistently across the three
	part-books. The variant “forza o d’arte” occurs again in T from
	reprint RISM B/I, 1604-13.

@COMMENTARY:

	This three-voice piece by Roman composer Giovannelli appeared
	in the second book of the anthology <i>Fiori musicali</i>,
	assembled by Giacomo Vincenzi and dedicated to Francesco
	Sugana of Treviso.

	Like the first book of the anthology, it primarily features
	works by Roman and Venetian composers, many based on texts
	by Tasso.

	Giovannelli’s three-voice setting of “Non è questa la mano”
	is striking not only for its liveliness &mdash; note the
	hectic repetition of rhythmic-melodic motives in {{mm 30 33}}
	&mdash; but also for its ingenuous word painting.

	In particular, Giovannelli gives a musical representation
	of the poem’s subject, the female hand, by referencing the
	Guidonian hand at the beginning and at the end of the setting
	&mdash; note the <i>hexachordum durum</i> G-E in {{mm 1 2}}
	and {{mmx 5 6}} in C and B, respectively, and the <i>hexachordum
	naturale</i> C-A in {{mm 2 4}} (ascending) and {{mm 30 31}}
	(descending) in the T and B, respectively.

	Giovannelli may have borrowed this idea from Marenzio, whose
	1581 setting of the same poem also features hexachords (see
	{{work "Trm0047b"}}).


@@END: CRICITAL_REPORT
```

Note that the original clefs will be encoded into a spreadsheet, and then migrated into a settings index (in `/data/indexes/*-settings.aton`) as well as the mensuration signs, so these will not need to be included in the critical report files again (I will extract them from the settings index data).

Here is the raw template with the content stripped out:

```
@@BEGIN: CRITICAL_REPORT
@CATALOGNUM:
@PRINCIPAL_SOURCE:
@OTHER_SOURCE:
@OTHER_SOURCE: 
@OTHER_SOURCE: 
@OTHER_SOURCE: 
@OTHER_SOURCE: 
@EMENDED_READING: 
@CRITICAL_NOTE:
@CRITICAL_NOTE:
@COMMENTARY:
@@END: CRICITAL_REPORT
```

The report starts and ends with `@@` markers.  The parameters inside these `BEGIN` and `END` markers can be in any order.   The TMP catalog number of the work is in `@CATALOGNUM:`.

Principal sources are in one (or more) `@PRINCIPAL_SOURCE:` fields.  Other sources are in one or more `@OTHER_SOURCE:` fields.  When a line break is needed in one of these entries `<br>` is used.  If italics are needed then `<i>` and `</i>` enclose the text to be italicized.

`@EMENDED_READING:` is used to add an emended reading note (multiple fields if more than one).

`@CRITICAL_NOTE:` is used for each critical note

`@COMMENTARY:` is for the commentary section, using `<p>` to start a new paragraph.  In this case I separated out the sentences with blank lines between them, but they would merge into a single paragraph since there is no `<p>` between them.

I added a new template macro called "siglum", such as `{{siglum "B-Br"}}`.  These will expand into the full name of the institution and country.  But to do that, we will need to make a spreadsheet of all of the siglum that are referenced (and then converted to an ATON file on the website in `/data/support/sigla.aton`.  Note that the siglum has to be enclosed in quotes, unlike the measure numbers in mm template macros.

There is a general problem with dashes that should be dealt with in a systematic way.  Hyphens should be encoded as hyphens, but n-dashes and m-dashes should probably best be encoded as either `&ndash;` and `&mdash;` or as `--` and `---` (the last method will be more readable in Word).

All of this can be done in M$ Word, but then it would be copied into a file created on the Github website.  This one would be called `/data/reports/Trm0047m.aton`, for example.  The main thing to take account of is that visual italics will not copy/paste from Word into the Github editor (which is why HTML italic tags `<i>` and `</i>` are needed.  Also there are probably complications dealig with n-dashes, m-dashes (as mentioned above) as well as quotes (there are left/right quotes in the sample template content which come from Word, and they are displaying properly on the website, but we would have to be careful about not mixing with plain straight quotes.  Similarly for apostrophes.

Once the new template system is set up, adding the file to Github in `/data/reports` will automatically place the contents of the template on the corresponding work page.  `Trm0047m.aton` will appear on http://www.tassomusic.org/work?id=Trm0047m for example.  As we tested out last week, it can take up to 10 minutes for the website to update if Github is busy, so it will not actually be instantaneous.

**Comment by craigsapp** [comment]
Note that original clefs and mensurations will be extracted from the spreadsheet in the OCLEFS and OTIME columns:

https://docs.google.com/spreadsheets/d/1YcaAQc-mxFFDWyOsT7HOlwZkEqB4rPEuOzXCMTKprMc/edit#gid=1098021743

which is where the voices/extant voices will be entered (although we will discuss voices on Monday).

<img width="1105" alt="screen shot 2017-04-08 at 10 43 32 pm" src="https://cloud.githubusercontent.com/assets/3487289/24835107/d2d24388-1cac-11e7-8a86-d7ffc0432c8c.png">

**Comment by craigsapp** [comment]
The new system for critical reports is in place.  

The example template (not much has changed):

https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/data/reports/Trm0047m-report.aton

This can be further refined as needed.

```
@@BEGIN: CRITICAL_REPORT

@CATALOGNUM: Trm0047m

@PRINCIPAL_SOURCE:
	<i>Fiori musicali di diversi auttori a tre voci.
	Libro secondo. Nuovamente composti, & dati in luce</i>.
	Venice: Giacomo Vincenzi, 1588 (RISM B/I, 1588-20)
	<br>
	[Princeps edition --- complete: CTB]
	<br>
	Digital reproduction of exemplar from {{siglum "A-Wn"}}

@OTHER_SOURCE:
	<i>Fiori musicali di diversi auttori a tre voci. Libro secondo.
	Nuovamente ristampati</i>. Venice: Giacomo Vincenti, 1598 (RISM B/I, 1598-10)
	<br>
	[Reprint of RISM B/I, 1588-20 --- complete: CTB]

@OTHER_SOURCE: Microfilm reproduction of exemplar from {{siglum "I-Bc"}}

@OTHER_SOURCE: <i>Fiori musicali a tre voci de diversi eccellentissimi auttori.
	Di nuovo stampati & seguendo l’ordine de suoi Tuoni posti in luce</i>.
	Antwerp: Pietro Phalesio, 1604 (RISM B/I, 1604-13)
	<br>
	[Pierre Phalèse’s reprint of the first and second books of the anthology
	<i>Fiori musicali</i> --- complete: CTB]

@OTHER_SOURCE: CB – Microfilm reproduction of exemplar from {{siglum "B-Br"}}

@OTHER_SOURCE: T – Digital reproduction of exemplar from {{siglum "DK-Kk"}}

@EMENDED_READING: None

@CRITICAL_NOTE: {{MM 14}} and {{MMx 18}}, T, text reads “forza o d’arte”
	and “forza od arre,” respectively.

@CRITICAL_NOTE: In corresponding sections from reprint RISM B/I,
	1598-10, text reads “forza d’arte” consistently across the three
	part-books. The variant “forza o d’arte” occurs again in T from
	reprint RISM B/I, 1604-13.

@COMMENTARY:

	This three-voice piece by Roman composer Giovannelli appeared
	in the second book of the anthology <i>Fiori musicali</i>,
	assembled by Giacomo Vincenzi and dedicated to Francesco
	Sugana of Treviso.

	Like the first book of the anthology, it primarily features
	works by Roman and Venetian composers, many based on texts
	by Tasso.

	Giovannelli’s three-voice setting of “Non è questa la mano”
	is striking not only for its liveliness --- note the
	hectic repetition of rhythmic-melodic motives in {{mm 30 33}}
	--- but also for its ingenuous word painting.

	In particular, Giovannelli gives a musical representation
	of the poem’s subject, the female hand, by referencing the
	Guidonian hand at the beginning and at the end of the setting
	--- note the <i>hexachordum durum</i> G-E in {{mm 1 2}}
	and {{mmx 5 6}} in C and B, respectively, and the <i>hexachordum
	naturale</i> C-A in {{mm 2 4}} (ascending) and {{mm 30 31}}
	(descending) in the T and B, respectively.

	Giovannelli may have borrowed this idea from Marenzio, whose
	1581 setting of the same poem also features hexachords (see
	{{work "Trm0047b"}}).


@@END: CRITICAL_REPORT
```

which is rendered on the page:

http://www.tassomusic.org/work/?id=Trm0047m

<img width="583" alt="screen shot 2017-04-10 at 11 34 50 pm" src="https://cloud.githubusercontent.com/assets/3487289/24895730/cb710e3a-1e46-11e7-8e94-043b970066e3.png">

This is nearly identical to the old template which uses HTML:

<img width="575" alt="screen shot 2017-04-10 at 11 34 43 pm" src="https://cloud.githubusercontent.com/assets/3487289/24895742/d6cbe098-1e46-11e7-88da-40225a248acb.png">


The only real difference other than some line break changes is the display of the mensuration sign as "c" rather than "C".  It might be nice to do the mensuration in lower case so that the Cut-C can be displayed as on the census page:

<img width="46" alt="screen shot 2017-04-10 at 11 40 12 pm" src="https://cloud.githubusercontent.com/assets/3487289/24895815/11a8c3c0-1e47-11e7-875c-2b56395a23dd.png">

(Cut-C is displayed by overlapping "c" and "|" over each other.  It does not look as nice with "C" since the line will not extend as far.

Sigla
=======

Library sigla are stored on the website in the file:

https://github.com/TassoInMusicProject/tasso-website/tree/gh-pages/data/support/sigla.aton

which currently has the contents:

```
@@START: SIGLUM
@SIGLUM:	A-Wn
@INSTITUTE:	Österreichische Nationalbibliothek
@INSTITUTE_ENGLISH:	Austrian National Library
@@END: SIGLUM

@@START: SIGLUM
@SIGLUM:	I-Bc
@INSTITUTE:	Museo Internazionale e Biblioteca della Musica, Bologna
@INSTITUTE_ENGLISH:	International Museum and Library of Music, Bologna
@@END: SIGLUM

@@START: SIGLUM
@SIGLUM:	B-Br
@INSTITUTE:	Bibliothèque royale de Belgique, Bruxelles
@INSTITUTE_ENGLISH:	Royal Library of Belgium, Brussels
@@END: SIGLUM

@@START: SIGLUM
@SIGLUM:	DK-Kk
@INSTITUTE:	Det Kongelige Bibliotek, Copenhagen
@INSTITUTE_ENGLISH:	The Royal Library, Copenhagen
@@END: SIGLUM
```

You can either add new sigla to this file or on the spreadsheet

https://docs.google.com/spreadsheets/d/1YcaAQc-mxFFDWyOsT7HOlwZkEqB4rPEuOzXCMTKprMc/edit#gid=1098021743

And I will transfer to them to the sigla.aton file.

The `@INSTITUTE_ENGLISH:` field is optional, and I can remove it if not wanted.

In the report templates, a sigla would be added like this: `{{siglum "A-Wn"}}`, which would expand into `Österreichische Nationalbibliothek (A-Wn)` by extracting the `@INSTITUTE:` parameter from the sigla.aton file for `A-Wn`.  Note that the siglum must be in quotes.

Mensuration and Original clefs
=========================

Mensuration signs and clefs in the principal source will be extracted from the rime settings index file:

https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/data/indexes/rime-settings.aton

Here is the entry for Trm0047m:

```
@@BEGIN:	RIME_SETTING
@CATALOGNUM:	Trm0047m
@RIMETITLE:	Non è questa la mano
@SOLERTI:	47
@COMPOSER:	Giovannelli, Ruggiero
@COMDATES:	
@PRINCEPSTITLE:	In fiori musicali, libro secondo
@PRINCEPSLOC:	Venetia
@NORMLOC:	Venice
@PRINCEPSPUB:	Vincenzi
@PRINCEPSYEAR:	1588
@PRINCEPSRISM:	1588-20
@REPRINTS:	1598-10, 1604-13
@OCLEFS:	             C (G2) T (C2) B (C3)
@OMENSURATION:    C	
@OKEYSIG:	
@NOTE:		
@@BEGIN:	VERSES
@VERSE:
	Non è questa la mano
	Che tant’e sì mortali
	Aventò nel mio cor fiammell’e strali?
	Ecco che pur si trova
	Fra le mie man ristretta,
	Né forza d’arte per fuggir le giova,
	Né tien face o saetta
	Che da me la difenda.
	Giust’è ben ch’io ne prenda,
	Amor, qualche vendetta,
	E se piaghe mi diè, baci le renda.
@@END:		VERSES
@@BEGIN:	TRANSLATION
@VERSE:
	Isn’t this the hand
	That hurled so many fatal
	Flames and arrows at my heart?
	Yet behold where it is,
	Held fast in my hands,
	Where no power or artifice can help it escape,
	Nor can it grasp a torch or a spear
	To defend itself against me.
	It’s only fair that I should have
	Some kind of revenge, o Love,
	And if she gave me wounds, I’ll give her kisses.
@@END:		TRANSLATION
@@END:		RIME_SETTING
```

Specifically the lines:

```
@OCLEFS:	     C (G2) T (C2) B (C3)
@OMENSURATION:    C	
```

Currently the clefs are separated by spaces, but these could be changed to commas or similar if you want, otherwise the pattern is voice abbreviation, then space then clef name in parentheses), then space, then next voice information.

The Mensuration should be "C" for C mensuration (not lower case), and "Cut-C" for cut-c (not lower case).  I presume eventually there will be some "O" mensurations as well.

HTML formatting codes
===================

Here are the formatting codes which you will need:

`<i>...</i>` == make the text inside the two tags `<i>` and `</i>` italic.

`<br>` force a line break at this current location in the text

Special character sequences:

Dashes
========

`---` this represents an m-dash (a dash the width of the letter "m") This is a dash used for separating text.

`--` this represents an n-dash.  This is used for a range of numbers, or birth/death dates of a composer.

`-` hyphen.  This is used for hyphens.  RISM numbers use hyphens not n-dashes.

Word can produce n-dashes and m-dashes, but preferrably the above system will be used to select the desired hyphen.   This is because it is difficult to control the character mapping between software, such as in particular Word and other programs.  For macOS copy/paste it should not be too much of a problem since the text *should* be copied as UTF-8 characters (which are what the website uses).   But sometimes things like apostrophes coming from Word are displayed incorrectly on the web (so ideally it would be nice to avoid special characters in Word to minimize the problem).

Repeated entries in the template
=========================

Here is the report template without any content:

```
@@BEGIN: CRITICAL_REPORT
@CATALOGNUM:
@PRINCIPAL_SOURCE:
@OTHER_SOURCE:
@OTHER_SOURCE:
@OTHER_SOURCE:
@OTHER_SOURCE:
@OTHER_SOURCE:
@EMENDED_READING:
@CRITICAL_NOTE:
@CRITICAL_NOTE:
@COMMENTARY:
@@END: CRITICAL_REPORT
```

The parameters can be in any order except for the BEGIN/END lines.  When there are more than one entry for `PRINCIPAL_SOURCE`, `OTHER_SOURCE`, `EMENDED_READING`, `CRITICAL_NOTE`, or `COMMENTARY`, the multiple components will be displayed sequentialy in their respective sections of the critical report, and each separated by a blank line.  `CATALOGNUM` is required in order to access the information about mensurations and clefs from the `rime-setting.aton` file (otherwise they will no be printed in the critical report).

Data for each parameter starts after the colon, and the content ends at the next `@` line,  Indenting in the example report is only for readability and is not necessary (Word will have difficulty producing the hard returns used in this case, but it won't matter how the linebreaks are done).
