### ISSUE TITLE
Add our names to frontpage

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#34]

**Comment by craigsapp** [comment]
Done.

Old header:
<img width="1143" alt="screen shot 2017-04-17 at 8 11 12 pm" src="https://cloud.githubusercontent.com/assets/3487289/25113066/0ac94684-23aa-11e7-9585-69a997a3b801.png">


New header:

<img width="1143" alt="screen shot 2017-04-17 at 8 10 43 pm" src="https://cloud.githubusercontent.com/assets/3487289/25113064/fe1a6490-23a9-11e7-9ba2-1c53a426df3a.png">

**Comment by emilianoricciardi** [comment]
Looks good. Maybe we can use bold for "Digital Edtion...," so that it will
look different from our names and more similar to the title?

**Comment by craigsapp** [comment]
"Digital Edition..." is already bold.  Here is what it looks like unbolded:

<img width="1146" alt="screen shot 2017-04-17 at 8 42 48 pm" src="https://cloud.githubusercontent.com/assets/3487289/25113762/9206320c-23ae-11e7-9c42-dacb9f781565.png">

One possibility is to unbold the names:

<img width="1143" alt="screen shot 2017-04-17 at 8 43 05 pm" src="https://cloud.githubusercontent.com/assets/3487289/25113772/9d1f649c-23ae-11e7-84f2-d16ebbae749a.png">


I made the names bold because they are less readable, but  if you like the unbold names as shown above, I can do that.

**Comment by emilianoricciardi** [comment]
We can leave it as is, I think.
