### ISSUE TITLE
Additional poems/settings 

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#60]
See attached email exchange
[Gmail - Additional poems:settings for Tasso project.pdf](https://github.com/TassoInMusicProject/tasso-website/files/1383441/Gmail.-.Additional.poems.settings.for.Tasso.project.pdf)

**Comment by craigsapp** [comment]
Emiliano says:

1) Under "Other Poems," add a new section for _Gerusalemme Conquistata_ (this is a revised version on _Gerusalemme
iberata_, which Tasso wrote in the late 1580s/early 1590s). For this section, indicate Canto/Ottava.
To my knowledge, there is only one poetic excerpt and a single setting to add to this section. The excerpt is "Piagn'e
sospira; e quand'i caldi raggi" (VIII/6), and the musical setting is: Claudio Monteverdi, _Il quarto libro dei madrigali a
cinque voci_ (Venice: Amadino, 1603).
2) Under "Rime," insert the poem "Qui dove fan le piante" (_Rime_ 1370). There is only one musical setting of this poem:
Camillo Cortellini, _Musica di Camillo Cortellini il violino_ (Bologna: Rossi, 1587).
3) Under "Di nettare amoroso ebro la mente" (_Rime_ 183), add the following setting (currently missing, but one never
knows, we might be able to trace it one day): 
Antonio Cirullo, _Il secondo libro de madrigali a cinque voci_ (Venice: Vincenti, 1598)
4) Add the following manuscript setting to "Se 'l vostro volto è d'un'aria gentile" (_Rime_297):
Cosimo Bottegari (?), Ms. C311, late 16th century. Because of the uncertain dating, I would place it before the Aagesen
setting.
5) Add the following piece to "O vaga tortorella" (_Rime_ 399):
Biagio Marini, _Madrigaletti a una, due, tre e quatro voci, con alcune villanelle. Libro quinto. Opera nona_ (Venice: Magni,
1635)
6) For "Io son la Primavera"  (_Rime_ 361), add the following setting:
Giovanni Stefani, _Scherzi amorosi. Canzonette ad una voce sola. Libro secondo_ (Venice: Vincenti, 1620)

**Comment by craigsapp** [comment]
Notes related to the above additions (see initial PDF for graphic images and better formatting):

I have finally (!) added the new works to the index file:
https://github.com/TassoInMusicProject/tasso­website/blob/gh­pages/data/indexes/rime­settings.aton
And all of them except #1 are now visible on the TiM website:
1) Under "Other Poems," add a new section for _Gerusalemme Conquistata_ (this is a revised version on
_Gerusalemme iberata_, which Tasso wrote in the late 1580s/early 1590s). For this section, indicate Canto/Ottava.
To my knowledge, there is only one poetic excerpt and a single setting to add to this section. The excerpt is "Piagn'e
sospira; e quand'i caldi raggi" (VIII/6), and the musical setting is: Claudio Monteverdi, _Il quarto libro dei madrigali a
cinque voci_ (Venice: Amadino, 1603).
Added as Tco0806a, but will take time to get displayed on the website under Others/Gerusalemme Conquistata.
Should it be "Gerusalemme Conquistata" or "Gerusalemme conquiestata" (with upper or lower case for the C)?
2) Under "Rime," insert the poem "Qui dove fan le piante" (_Rime_ 1370). There is only one musical setting of this
poem: Camillo Cortellini, _Musica di Camillo Cortellini il violino_ (Bologna: Rossi, 1587).
Added as Trm1370a.
What does "il violino" mean?  That there is no lyrical text?  or that this is the violin part, or that this is to be played also
with violin, or that Cortellini was a violinist?
Is there a RISM number?
What is the literary genre for Rime 1370?
What are the manuscript and print sources for Rime 1370?
http://www.tassomusic.org/settings/?rime=1370
Rime 1370 listing on Homepage:
N.B.: for adding a new rime to the homepage index, the poem has to be added to data/indexes/rime­verses.aton:
https://github.com/TassoInMusicProject/tasso­website/blob/gh­pages/data/indexes/rime­verses.aton
Currently the new entry for  Rime 1370 does not have any verses listed:
https://github.com/TassoInMusicProject/tasso­website/blob/gh­pages/data/indexes/rime­verses.aton#L4189­L4197
3) Under "Di nettare amoroso ebro la mente" (_Rime_ 183), add the following setting (currently missing, but one never
knows, we might be able to trace it one day): 
Antonio Cirullo, _Il secondo libro de madrigali a cinque voci_ (Venice: Vincenti, 1598)
Added as Trm0183e
Is the princeps location "Venice", that seems like the normalized location.
Is there still a RISM number for the work if it is lost?
http://www.tassomusic.org/settings/?rime=183
4) Add the following manuscript setting to "Se 'l vostro volto è d'un'aria gentile" (_Rime_297):
Cosimo Bottegari (?), Ms. C311, late 16th century. Because of the uncertain dating, I would place it before the Aagesen
setting.
Added as Trm0297e.
The rime title of the other settings is:
    Se ’l vostro volto è d’un aria gentile
d'un'aria seems strange if the last word is "aria".   If it is "naria", then of course there should be a contraction.  Should the
other rime title for the other settings be changed to d'un'aria, or this one changed to d'un aria?
> Because of the uncertain dating, I would place it before the Aagesen setting.
You mean in the listing of settings?  In other words this one should be listed first for Rime 297 settings?
http://www.tassomusic.org/settings/?rime=297
5) Add the following piece to "O vaga tortorella" (_Rime_ 399):
Biagio Marini, _Madrigaletti a una, due, tre e quatro voci, con alcune villanelle. Libro quinto. Opera nona_ (Venice:
Magni, 1635)
Added as Trm0399b.
Is there a RISM number for the princeps or reprint? 
This is from an anthology as opposed to a volume dedicated to the same composer?   This is important to add the "In" in
non­italic type for the source:
http://www.tassomusic.org/settings/?rime=399
6) For "Io son la Primavera"  (_Rime_ 361), add the following setting:
Giovanni Stefani, _Scherzi amorosi. Canzonette ad una voce sola. Libro secondo_ (Venice: Vincenti, 1620)
Added as Trm0361c.  
http://www.tassomusic.org/settings/?rime=361
Is there a RISM number for this edition?  Is the original spelling of the publication location "Venice"?  (that is possibly the
normalized location).
Most of the other titles are in this format:
         Il secondo libro de canzonette ad una voce sola

**Comment by craigsapp** [comment]
Reply from Emiliano to above comments:

below are the answers to your queries:

1) Title should be "Gerusalemme conquistata" (with lower case ­c)

2) "Il Violino" is Cortellini's nickname, as indicated in the source title. To my knowledge, there is no RISM number for this
source (it was found in the Rome National Library in the 80s, but never made it into databases). I'll double check and ask
my colleague in Rome who found it, though.
The literary genre of Rime 1370 is madrigale. The manuscript source for this poem is a letter by Torquato Tasso to Giulio
Segni, dated June 23, 1587. To my knowledge, there are no printed sources.

3) The non­normalized place of publication for Trm0183e is "Venetia." This applies also Trm1497a, which appears in the
same source. The source is lost and there appears to be no RISM number associated with it.

4) The mistake is in the poem's title as spelled in the list of poems and at the top of the list of settings. It should be "Se'l
vostro volto è d'un'aria gentile."
In the list of settings, I'd put Bottegari's (which dates from the late 16th century) before Aagesen (which is after 1600)

5) This is a single­author source. The original place of publication is Venetia. The RISM number is M0664.

6) We need to revise the title. This is an anthology assembled by Giovanni Stefani. The author of the song is unknown. So
I'd put a question mark for author and give the following title for the source: In Scherzi amorosi. Canzonette
ad una voce sola. Poste in Musica da diuersi, e raccolte da Giovanni Stefani. Libro secondo. The original place of
publication is Venetia. The 1620 princeps is lost, but we do have the RISM # of the 1622 reprint (RISM B/I 1622­12).

**Comment by craigsapp** [comment]
> 1) Under "Other Poems," add a new section for Gerusalemme Conquistata (this is a revised version on Gerusalemme liberata, which Tasso wrote in the late 1580s/early 1590s). For this section, indicate Canto/Ottava.  To my knowledge, there is only one poetic excerpt and a single setting to add to this section. The excerpt is "Piagn'e sospira; e quand'i caldi raggi" (VIII/6), and the musical setting is: Claudio Monteverdi, Il quarto libro dei madrigali a cinque voci (Venice: Amadino, 1603).

Done in commit https://github.com/TassoInMusicProject/tasso-website/commit/a315b25405d9247a3ac12935444edfcc395b9fe5

Result on the homepage display in the other settings tab:

<img width="573" alt="screen shot 2017-11-10 at 9 34 47 am" src="https://user-images.githubusercontent.com/3487289/32670960-6bdd0120-c5fa-11e7-8829-9e1e7287ae2b.png">



To add a new entry to the "Other poems" section:

(1) Add a `@GROUP` field in the entry of the setting in the file https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/data/indexes/other-settings.aton

Such as in this case:

```
@@BEGIN: CONQUISTATA
@GROUP: Gerusalemme conquistata
@CATALOGNUM:    Tco0806a
@CANTO: VIII
@OTTAVA:        6
@TITLE: Piagn'e sospira; e quand'i caldi raggi
@COMPOSER:      Monteverdi, Claudio
@COMDATES:      1567-1643
@PRINCEPSTITLE: Il quarto libro dei madrigali a cinque voci
@PRINCEPSLOC:   Venice
@NORMLOC:       Venice
@PRINCEPSPUB:   Amandino
@PRINCEPSYEAR:  1603
@PRINCEPSRISM:
@VOICES:        5
@REPRINTS:
@@END: CONQUISTATA
```
(2) in `/scripts-local.html` add a function which extracts indexing information about the other genre:

```javascript
//////////////////////////////
//
// makeConquistataList --
//

function makeConquistataList(gllist) {
console.log("conquistataList = ", gllist);
   var output = {};
   var data = output;

   if (!gllist.length) {
      gllist = [gllist];
   }
   for (var i=0; i<gllist.length; i++) {
      var key = gllist[i].CATALOGNUM.replace(/[a-z]$/, "");
      data[key] = {};
      data[key].ctitle = gllist[i].TITLE;
      data[key].canto  = gllist[i].CANTO;
      data[key].ottava = gllist[i].OTTAVA;
      data[key].catalogbase = key;
   }
   // Should already be sorted, but maybe sort here by Canto/Ottava
   // as stored in catalog number.
   return output;
}
```
(3) Create a template in `/templates.html` for displaying entries in the new genre list:

```html
<!-- conquistata-template
      The gerusalemme conquistatatemplate is used to fill in the list of poems
      on the homepage.  The list of poems is found in the file
      /data/indexes/other-settings.json.
-->

{% raw %}
<script id="conquistata-template" type="text/x-handlebars-template">
   <table class="poem-list">
   <thead>
      <th onclick="sortByNumber(0)" style="cursor:pointer">Canto/Ottava</th>
      <th style="cursor:pointer"><span onclick="sortByText(1)">Title</span></th>
   <thead>
   <tbody>
   {{#each this}}

   <tr>
      <td style="text-align:left;">
         <table style="width:100px">
         <tr>
         <td style="width:30px; text-align:right;">
            <span class="canto nowork"><nobr>{{canto}}</nobr></span>
         </td>
         <td style="width:70px; text-align:right;">
            <span class="verse nowork"><nobr>{{ottava}}</nobr></span>
         </td>
         </tr>
         </table>
      </td>
      <td class="nowork" onmouseover="show(this)" onmouseout="hide(this)">{{{ctitle}}}
         <table class="choices">
         <tr>
            <td><a href=/settings?id={{number catalogbase}}>Musical Settings</a></td>
            <td><a href=/sources?id={{number catalogbase}}>Literary Sources</a></td>
            <td><a href=/variants?id={{number catalogbase}}>Literary Variants</a></td>
         </tr>
         </table>
      </td>
   </tr>


   {{/each}}
   </tbody>
   </table>
</script>
{% endraw %}
```



(4) In `/scripts-local.html` add the other gene to the function that create the other repertory list:

```javascript
function continueProcessingOther(element) {
   var csource = document.querySelector("#conquistata-template").textContent;
   var esource = document.querySelector("#ecloghe-template").textContent;
   var rsource = document.querySelector("#rinaldo-template").textContent;
   var lsource = document.querySelector("#lagrime-template").textContent;
   var tsource = document.querySelector("#torrismondo-template").textContent;

   var conquistataTemplate = Handlebars.compile(csource);
   var eclogheTemplate = Handlebars.compile(esource);
   var rinaldoTemplate = Handlebars.compile(rsource);
   var lagrimeTemplate = Handlebars.compile(lsource);
   var torrismondoTemplate = Handlebars.compile(tsource);

   var conquistatalist = makeConquistataList(OTHERLIST.CONQUISTATA);
   var ecloghelist = makeEclogheList(OTHERLIST.ECLOGHE);
   var rinaldolist = makeRinaldoList(OTHERLIST.RINALDO);
   var lagrimelist = makeLagrimeList(OTHERLIST.LAGRIME);
   var torrismondolist = makeTorrismondoList(OTHERLIST.TORRISMONDO);

   var output = "<h2 style='margin-left:100px'>Ecloghe</h2>";
   output += eclogheTemplate(ecloghelist);
   output += "<h2 style='margin-top:-80px; margin-left:100px'>Rinaldo</h2>";
   output += rinaldoTemplate(rinaldolist);
   output += "<h2 style='margin-top:-80px; margin-left:100px'>Lagrime della Beata Vergine</h2>";
   output += lagrimeTemplate(lagrimelist);
   output += "<h2 style='margin-top:-80px; margin-left:100px'>Re Torrismondo</h2>";
   output += torrismondoTemplate(torrismondolist);
   output += "<h2 style='margin-top:-80px; margin-left:100px'>Gerusalemme conquistata</h2>";
   output += conquistataTemplate(conquistatalist);
   element.innerHTML = output;
   showTab("other-heading");
}
```

**Comment by craigsapp** [comment]
> 3) The non­normalized place of publication for Trm0183e is "Venetia." This applies also Trm1497a, which appears in the same source. The source is lost and there appears to be no RISM number associated with it.

Done in commit: https://github.com/TassoInMusicProject/tasso-website/commit/d36eb62d31093125bf49b72af8b6b2211d584a7f

File where update was made:

https://github.com/TassoInMusicProject/tasso-website/blob/gh-pages/data/indexes/rime-settings.aton
