### ISSUE TITLE
Fix hyperlinks of literary prints

### ISSUE THREAD

**Issue by emilianoricciardi** [TassoInMusicProject/tasso-website#92]
I have entered several hyperlinks for Rime literary prints. I used what we did for literary manuscripts as a model (i.e., added @URL fields), but the hyperlinks don't show in the webpage. Can you look into this?

**Comment by craigsapp** [comment]
Done (!).

Example:

http://www.tassomusic.org/sources/?rime=3

Print 8 now has a hyperlink:

<img width="1039" alt="screen shot 2018-06-22 at 10 46 46 am" src="https://user-images.githubusercontent.com/3487289/41791043-5ab93322-7609-11e8-8456-d50681387848.png">

which opens up a new tab for the URL:

<img width="1131" alt="screen shot 2018-06-22 at 10 49 32 am" src="https://user-images.githubusercontent.com/3487289/41791076-7cbc85f0-7609-11e8-9f85-233bc7e7c637.png">

Fixed with commit https://github.com/TassoInMusicProject/tasso-website/commit/eed15df7a8dfac78f1d9f933d78ad36d5a5db111
